secrets:
  db:
    host: localhost
    port: 5432
    db: ls
    user: icfcusr
    password: password
    logging: true
    debug: true
params:
  gql:
    playground: true
  application:
    port: 3100
  logger:
    level: trace
    transport:
      target: pino-pretty
